name: Build And Test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'
      - 'main'
    paths-ignore:
      - '.github/**'
      - '**.md'
  push:
    branches:
      - 'feature/**'
      - 'enhancement/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'main'
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.13'
          distribution: 'adopt'
          cache: maven
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots verify
